version: "3.8"

services:
    
    database:
        image: mariadb:10.3.38
        container_name: database_docker_symfony
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MARIADB_USER=root
            - MARIADB_PASSWORD=secret
            - MARIADB_ROOT_PASSWORD=secret
            - MARIADB_DATABASE=symfony
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=secret
        networks:
            - dev
    
    redis:
        image: redis:latest
        container_name: redis_docker_symfony
    
    www:
        build:
            context: .
            dockerfile: Dockerfile
            target: app_php
        container_name: www_docker_symfony
        ports:
            - "8000:80"
        volumes:
#            - var/www/app/vendor
            - ./:/var/www/app
        environment:
            REDIS_HOST: redis
            REDIS_PORT: ${REDIS_PORT}
        depends_on:
            - database
            - phpmyadmin
            - mailhog
            - redis
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
