version: "3.8"

services:
    
    database:
        image: mariadb:10.3.38
        container_name: database_docker_symfony
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: unless-stopped
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=secret
        networks:
            - dev
    
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog_docker_symfony
        restart: unless-stopped
        ports:
            - "8082:8025"
            - "1025:1025"
        networks:
            - dev
                
    redis-stack:
        image: redis/redis-stack
        container_name: redis_stack_docker_symfony
        restart: unless-stopped
        ports:
            - "6379:6379"
            - "8081:8001"
        volumes:
            - redis-data:/data
        networks: 
            - dev
    
    www:
        build:
            context: .
            dockerfile: Dockerfile
            target: app_php_dev
        container_name: www_docker_symfony
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/app
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            REDIS_HOST: redis-stack
            REDIS_PORT: ${REDIS_PORT}
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
        extra_hosts: 
            - host.docker.internal:host-gateway # Ensure that host.docker.internal is correctly defined on Linux
        depends_on:
            - database
            - phpmyadmin
            - mailhog
            - redis-stack
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
    redis-data:
