version: "3.8"

services:

  database:
    image: mysql
    container_name: database_docker_symfony
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=your_password
    networks:
      - dev

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_docker_symfony
    restart: always
    ports:
      - "1080:8025"
    networks:
      - dev

  www:
    build: docker
    container_name: www_docker_symfony
    ports:
      - "8000:80"
    volumes:
      - ./apache/vhosts:/etc/apache2/sites-enabled
      - ./project:/var/www/project
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: