version: "3.8"

services:
    
    database:
        image: mariadb:10.3.38
        container_name: database_docker_symfony
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: unless-stopped
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=secret
        networks:
            - dev
    
#    mailhog:
#        image: mailhog/mailhog
#        container_name: mailhog_docker_symfony
#        restart: always
#        ports:
#            - "1080:8025"
#        networks:
#            - dev
    
    www:
        build:
            context: .
            dockerfile: Dockerfile
            target: app_php_dev
        container_name: www_docker_symfony
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/app
#        environment:
#            PHP_IDE_CONFIG: serverName=localhost
#            APP_ENV: dev
#            REDIS_URL: redis://redis
#            MAILER_DSN: smtp://mail:1025?encryption=null&auth_mode=null
#            DATABASE_URL: mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=10.11.2-MariaDB&charset=utf8mb4
#            MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
#            MESSENGER_TRANSPORT_FAILED_DSN: redis://redis:6379/messages_failed
#        depends_on:
#            - database
#            - phpmyadmin
#            - mailhog
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
